30 elevation in database
Murmeldyret/DUNK pull request #34
Opened 2024-05-08 12:27 UTC by Murmeldyret

2024-05-08 12:41 UTC, Uewotm90 requested changes
kom i gang

2024-05-08 12:41 UTC, Uewotm90 commented on feature_database/migrations/2024-05-06-095729_transform/up.sql
> +  "dataset_name" VARCHAR(64) NOT NULL,
```suggestion
  "dataset_name" TEXT NOT NULL,
```
varchar 🤮

2024-05-08 12:41 UTC, Uewotm90 commented on feature_database/src/elevationdb.rs
> +            .map(|element| element.unwrap())
```suggestion
            .map(|element| element.expect("Donau"))
```

2024-05-08 12:41 UTC, Uewotm90 commented on feature_database/src/elevationdb.rs
> +        let transform: GeoTransform = transform.try_into().unwrap();
```suggestion
        let transform: GeoTransform = transform.try_into().expect("hej malthe");
```

2024-05-08 12:41 UTC, Uewotm90 commented on feature_database/src/elevationdb.rs
> +    pub fn get_world_coordinates(
dokumentar plox

2024-05-08 12:41 UTC, Uewotm90 commented on feature_database/src/elevationdb.rs
> +        let inv_ele = elevation_transform.invert().unwrap();
```suggestion
        let inv_ele = elevation_transform.invert().expect("giv grund her");
```

2024-05-08 12:41 UTC, Uewotm90 commented on feature_database/src/elevationdb.rs
> +        let upload_limit = insert_image.len() / 65535;
Magic number? 🤨 📸

2024-05-08 12:41 UTC, Uewotm90 commented on feature_database/src/lib.rs
> +        diesel::sql_query("DELETE FROM geotransform")
hvad fanden sker der her

2024-05-08 12:41 UTC, Uewotm90 commented on preprocessor/src/main.rs
> +        mosaic.lock().unwrap().set_elevation_dataset(&args.elevation_path.unwrap(), &temp_string).unwrap();
```suggestion
        mosaic.lock().expect("mutex?").set_elevation_dataset(&args.elevation_path.expect("io sjov"), &temp_string).expect("nice");
```
tredobbelt unwrap 😳

2024-05-08 12:41 UTC, Uewotm90 commented on preprocessor/src/main.rs
>      temp_dir.close().unwrap()
```suggestion
    temp_dir.close().expect("hov hov")
```

2024-05-08 12:41 UTC, Uewotm90 commented on preprocessor/src/main.rs
> +    elevation::add_elevation_data(conn, &mosaic.elevation.as_ref().unwrap()).unwrap();
```suggestion
    elevation::add_elevation_data(conn, &mosaic.elevation.as_ref().expect("reason")).expect("reasons");
```

2024-05-09 07:36 UTC, soft-MRJ commented on feature_database/src/elevationdb.rs
> +            .map(|element| element.unwrap())
Kan vi ikke give bare lidt bedre fejl besked også selvom det ikke kan lade sig gøre (så i det mindste skrive det)?

```suggestion
.map(|element| element.expect("Unreachable expect reached"))
```

```suggestion
.map(|element| element.expect("Failed to transform element"))
```

2024-05-09 07:40 UTC, soft-MRJ commented on feature_database/src/elevationdb.rs
> +        let transform: GeoTransform = transform.try_into().unwrap();
Kan vi ikke give bare lidt bedre fejl besked også selvom det ikke kan lade sig gøre (så i det mindste skrive det)?

2024-05-09 07:44 UTC, soft-MRJ commented on feature_database/src/elevationdb.rs
> +        let inv_ele = elevation_transform.invert().unwrap();
Kan vi ikke give en lidt mere seriøs fejl besked også selvom det ikke kan lade sig gøre (så i det mindste skrive det i fejl beskeden)?

2024-05-09 08:17 UTC, soft-MRJ commented on preprocessor/src/main.rs
> +        mosaic.lock().unwrap().set_elevation_dataset(&args.elevation_path.unwrap(), &temp_string).unwrap();
Kan vi ikke give en lidt mere seriøs fejl besked også selvom det ikke kan lade sig gøre (så i det mindste skrive det i fejl beskeden)?

2024-05-09 08:17 UTC, soft-MRJ commented on preprocessor/src/main.rs
>      temp_dir.close().unwrap()
Kan vi ikke give en lidt mere seriøs fejl besked også selvom det ikke kan lade sig gøre (så i det mindste skrive det i fejl beskeden)?

2024-05-09 08:17 UTC, soft-MRJ commented on preprocessor/src/main.rs
> +    elevation::add_elevation_data(conn, &mosaic.elevation.as_ref().unwrap()).unwrap();
Kan vi ikke give en lidt mere seriøs fejl besked også selvom det ikke kan lade sig gøre (så i det mindste skrive det i fejl beskeden)?

2024-05-10 06:57 UTC, Uewotm90 requested changes
lidt mere feedback

2024-05-10 07:04 UTC, Murmeldyret commented on feature_database/migrations/2024-05-06-095729_transform/up.sql
> +  "dataset_name" VARCHAR(64) NOT NULL,
Ain't gonna happen.

2024-05-10 07:27 UTC, Uewotm90 approved these changes
super 🏳️

2024-05-10 07:28 UTC, merged